# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_start', models.DateField(verbose_name='start date')),
                ('date_end', models.DateField(verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('time_hours_estimate', models.IntegerField(default=0)),
                ('time_hours_actual', models.IntegerField(default=0)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xptracker.Iteration')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xptracker.Developer')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xptracker.Story')),
            ],
        ),
    ]
