# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xptracker', '0004_auto_20170825_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xptracker.Iteration'),
        ),
    ]
