# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xptracker', '0008_task_iteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xptracker.Iteration'),
        ),
    ]
