# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xptracker', '0009_auto_20170826_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_hours_estimate',
            field=models.IntegerField(default=1),
        ),
    ]
