# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xptracker', '0011_auto_20170826_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xptracker.Developer'),
        ),
    ]
