# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xptracker', '0013_auto_20170826_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='time_hours_actual',
        ),
    ]
