# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xptracker', '0014_remove_story_time_hours_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xptracker.Developer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xptracker.Iteration'),
        ),
        migrations.AlterField(
            model_name='work',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xptracker.Developer'),
        ),
    ]
